name: Kerno Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Run Clippy linter
        run: cargo clippy -- -D warnings
      
      - name: Format check
        run: cargo fmt --check

      - name: Build release (Linux)
        run: cargo build --release

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Run Clippy linter
        run: cargo clippy -- -D warnings
      
      - name: Format check
        run: cargo fmt --check

      - name: Build release (Windows)
        run: cargo build --release
